name: buildx-on-pr

on:
  pull_request:
  workflow_dispatch:

env:
  PLATFORMS: linux/amd64 #,linux/arm64

jobs:
  buildx-on-pr:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Set up GO
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
