name: build-on-pr

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  packages: write

jobs:
  buildx-on-pr:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          fetch-depth: 0

      - name: Set up GO
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
